### ISSUE TITLE
Need 3.9 Python version ?

### ISSUE THREAD

**Issue by LinuxpowerLudo** [amor71/FINRAShortData#10]

**Comment by amor71** [comment]
> 

It should work fine in 3.9 .. are you having issues?

**Comment by LinuxpowerLudo** [comment]
> 

No i have only python 3.8 :) so i need absolutly 3.9 ?

**Comment by amor71** [comment]
3.8 should work just fine. On Dec 13, 2022, at 12:06 PM, LinuxpowerLudo ***@***.***> wrote:﻿


No i have only python 3.8 :) so i need absolutly 3.9 ?
